// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ping": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ping"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Header for requestID",
                        "name": "X-Request-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Header for body type",
                        "name": "Content-Type",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.PingResponse"
                        }
                    }
                }
            }
        },
        "/ping/:id/:param2": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ping"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "path params for id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "path params for param2",
                        "name": "param2",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "query for q",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.PingWithParam"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.PingResponse": {
            "type": "object",
            "properties": {
                "contentType": {
                    "type": "string",
                    "example": "application/json"
                },
                "message": {
                    "type": "string",
                    "example": "pong"
                },
                "requestId": {
                    "type": "integer",
                    "example": 123
                }
            }
        },
        "handlers.PingWithParam": {
            "type": "object",
            "properties": {
                "param": {
                    "type": "integer",
                    "example": 1
                },
                "param2": {
                    "type": "string",
                    "example": "action"
                },
                "q": {
                    "type": "string",
                    "example": "habib"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "KODA 3 GIN",
	Description:      "RESTful API created using gin for Koda Batch 3",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
