basePath: /
definitions:
  handlers.PingResponse:
    properties:
      contentType:
        example: application/json
        type: string
      message:
        example: pong
        type: string
      requestId:
        example: 123
        type: integer
    type: object
  handlers.PingWithParam:
    properties:
      param:
        example: 1
        type: integer
      param2:
        example: action
        type: string
      q:
        example: habib
        type: string
    type: object
  models.AuthData:
    properties:
      token:
        example: jwt token
        type: string
    type: object
  models.AuthResponse:
    properties:
      data:
        $ref: '#/definitions/models.AuthData'
      status:
        example: 200
        type: integer
      success:
        example: true
        type: boolean
    type: object
  models.BadRequestError:
    properties:
      error:
        example: error message
        type: string
      status:
        example: 400
        type: integer
      success:
        example: false
        type: boolean
    type: object
  models.InternalServerError:
    properties:
      error:
        example: error message
        type: string
      status:
        example: 500
        type: integer
      success:
        example: false
        type: boolean
    type: object
  models.StudentAuth:
    properties:
      nama_siswa:
        type: string
      password:
        minLength: 4
        type: string
    required:
    - nama_siswa
    - password
    type: object
host: localhost:3000
info:
  contact: {}
  description: RESTful API created using gin for Koda Batch 3
  title: KODA 3 GIN
  version: "1.0"
paths:
  /auth:
    post:
      consumes:
      - application/json
      parameters:
      - description: email and password input
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.StudentAuth'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.BadRequestError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.InternalServerError'
      tags:
      - auth
  /ping:
    get:
      parameters:
      - description: Header for requestID
        in: header
        name: X-Request-ID
        required: true
        type: integer
      - description: Header for body type
        in: header
        name: Content-Type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.PingResponse'
      tags:
      - ping
  /ping/:id/:param2:
    get:
      parameters:
      - description: path params for id
        in: path
        name: id
        required: true
        type: integer
      - description: path params for param2
        in: path
        name: param2
        required: true
        type: string
      - description: query for q
        in: query
        name: q
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.PingWithParam'
      tags:
      - ping
swagger: "2.0"
